"""empty message

Revision ID: 0279ea33563a
Revises: 1d3d42996d20
Create Date: 2024-11-04 13:07:20.130959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0279ea33563a'
down_revision: Union[str, None] = '1d3d42996d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan', sa.Column('contains_skin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan', 'contains_skin')
    # ### end Alembic commands ###
