"""empty message

Revision ID: 03e67372e9e2
Revises: 14a7c2797c30
Create Date: 2024-11-01 21:23:52.101113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e67372e9e2'
down_revision: Union[str, None] = '14a7c2797c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('experience_age', sa.String(), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_email'), 'doctor', ['email'], unique=True)
    op.create_index(op.f('ix_doctor_first_name'), 'doctor', ['first_name'], unique=False)
    op.create_index(op.f('ix_doctor_gender'), 'doctor', ['gender'], unique=False)
    op.create_index(op.f('ix_doctor_id'), 'doctor', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_last_name'), 'doctor', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_last_name'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_id'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_gender'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_first_name'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_email'), table_name='doctor')
    op.drop_table('doctor')
    # ### end Alembic commands ###
