"""empty message

Revision ID: 0e71d60a2ff6
Revises: dc49a8133b7a
Create Date: 2024-11-02 21:57:31.306067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e71d60a2ff6'
down_revision: Union[str, None] = 'dc49a8133b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task1', sa.String(), nullable=True),
    sa.Column('task2', sa.String(), nullable=True),
    sa.Column('task3', sa.String(), nullable=True),
    sa.Column('task4', sa.String(), nullable=True),
    sa.Column('task5', sa.String(), nullable=True),
    sa.Column('task6', sa.String(), nullable=True),
    sa.Column('task7', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_id'), 'test', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_id'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
