"""empty message

Revision ID: 1d3d42996d20
Revises: fbe4188b3096
Create Date: 2024-11-04 10:19:32.828458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d3d42996d20'
down_revision: Union[str, None] = 'fbe4188b3096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_scan', sa.Column('body_part', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_scan', 'body_part')
    # ### end Alembic commands ###
