"""empty message

Revision ID: 2768264f803e
Revises: 37f8fd259def
Create Date: 2024-11-05 03:04:04.512241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2768264f803e'
down_revision: Union[str, None] = '37f8fd259def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'has_segmentation')
    op.add_column('scan', sa.Column('segmentation_base64', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan', 'segmentation_base64')
    op.add_column('message', sa.Column('has_segmentation', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
