"""empty message

Revision ID: 37f8fd259def
Revises: f7aec5406578
Create Date: 2024-11-05 02:19:55.960099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f8fd259def'
down_revision: Union[str, None] = 'f7aec5406578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_scan', sa.Column('body_part', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_scan', 'body_part')
    # ### end Alembic commands ###
