"""empty message

Revision ID: 55e57614232e
Revises: 2a43032959e3
Create Date: 2024-11-05 14:12:00.555395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e57614232e'
down_revision: Union[str, None] = '2a43032959e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_scan', sa.Column('response', sa.String(), nullable=True))
    op.add_column('doctor_scan', sa.Column('recommendations', sa.String(), nullable=True))
    op.add_column('doctor_scan', sa.Column('type', sa.String(), nullable=True))
    op.add_column('doctor_scan', sa.Column('percent', sa.Float(), nullable=True))
    op.add_column('doctor_scan', sa.Column('result', sa.String(), nullable=True))
    op.create_index(op.f('ix_doctor_scan_recommendations'), 'doctor_scan', ['recommendations'], unique=False)
    op.create_index(op.f('ix_doctor_scan_response'), 'doctor_scan', ['response'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_scan_response'), table_name='doctor_scan')
    op.drop_index(op.f('ix_doctor_scan_recommendations'), table_name='doctor_scan')
    op.drop_column('doctor_scan', 'result')
    op.drop_column('doctor_scan', 'percent')
    op.drop_column('doctor_scan', 'type')
    op.drop_column('doctor_scan', 'recommendations')
    op.drop_column('doctor_scan', 'response')
    # ### end Alembic commands ###
