"""empty message

Revision ID: 59984541b2c6
Revises: 23505c45ea42
Create Date: 2024-11-04 23:41:54.079111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59984541b2c6'
down_revision: Union[str, None] = '23505c45ea42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan', sa.Column('response', sa.String(), nullable=True))
    op.add_column('scan', sa.Column('recommendations', sa.String(), nullable=True))
    op.add_column('scan', sa.Column('type', sa.String(), nullable=True))
    op.add_column('scan', sa.Column('percent', sa.Float(), nullable=True))
    op.add_column('scan', sa.Column('result', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan', 'result')
    op.drop_column('scan', 'percent')
    op.drop_column('scan', 'type')
    op.drop_column('scan', 'recommendations')
    op.drop_column('scan', 'response')
    # ### end Alembic commands ###
