"""empty message

Revision ID: 7fc5208f6540
Revises: 8cbab3c2f250
Create Date: 2024-11-01 18:09:18.298222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fc5208f6540'
down_revision: Union[str, None] = '8cbab3c2f250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('body_part', sa.String(), nullable=True),
    sa.Column('image_base64', sa.String(), nullable=True),
    sa.Column('ai_result', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_id'), 'scan', ['id'], unique=False)
    op.drop_index('ix_ai_message_id', table_name='ai_message')
    op.drop_table('ai_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('with_image', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('image_base64', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='ai_message_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ai_message_pkey')
    )
    op.create_index('ix_ai_message_id', 'ai_message', ['id'], unique=False)
    op.drop_index(op.f('ix_scan_id'), table_name='scan')
    op.drop_table('scan')
    # ### end Alembic commands ###
