"""empty message

Revision ID: 9760bef67295
Revises: c24497573315
Create Date: 2024-11-04 13:30:18.687775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9760bef67295'
down_revision: Union[str, None] = 'c24497573315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_scan', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('doctor_scan', sa.Column('age', sa.String(), nullable=True))
    op.add_column('doctor_scan', sa.Column('skin_type', sa.String(), nullable=True))
    op.add_column('doctor_scan', sa.Column('contains_skin', sa.Boolean(), nullable=True))
    op.drop_column('doctor_scan', 'body_part')
    op.drop_column('doctor_scan', 'size')
    op.drop_column('doctor_scan', 'how_many_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_scan', sa.Column('how_many_days', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('doctor_scan', sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('doctor_scan', sa.Column('body_part', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('doctor_scan', 'contains_skin')
    op.drop_column('doctor_scan', 'skin_type')
    op.drop_column('doctor_scan', 'age')
    op.drop_column('doctor_scan', 'gender')
    # ### end Alembic commands ###
