"""empty message

Revision ID: 9b2e33f9c061
Revises: 0e71d60a2ff6
Create Date: 2024-11-03 11:43:28.156857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2e33f9c061'
down_revision: Union[str, None] = '0e71d60a2ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('folder_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_folder_id'), 'scan_folder', ['id'], unique=False)
    op.add_column('scan', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.add_column('scan', sa.Column('size', sa.String(), nullable=True))
    op.add_column('scan', sa.Column('how_many_days', sa.String(), nullable=True))
    op.add_column('scan', sa.Column('have_pain', sa.Boolean(), nullable=True))
    op.add_column('scan', sa.Column('have_medicines', sa.Boolean(), nullable=True))
    op.add_column('scan', sa.Column('mixing', sa.String(), nullable=True))
    op.create_foreign_key(None, 'scan', 'scan_folder', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scan', type_='foreignkey')
    op.drop_column('scan', 'mixing')
    op.drop_column('scan', 'have_medicines')
    op.drop_column('scan', 'have_pain')
    op.drop_column('scan', 'how_many_days')
    op.drop_column('scan', 'size')
    op.drop_column('scan', 'folder_id')
    op.drop_index(op.f('ix_scan_folder_id'), table_name='scan_folder')
    op.drop_table('scan_folder')
    # ### end Alembic commands ###
