"""empty message

Revision ID: af8b72f948d3
Revises: 03e67372e9e2
Create Date: 2024-11-02 00:30:40.635997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8b72f948d3'
down_revision: Union[str, None] = '03e67372e9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('university', sa.String(), nullable=True))
    op.add_column('doctor', sa.Column('speciality', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'speciality')
    op.drop_column('doctor', 'university')
    # ### end Alembic commands ###
