"""empty message

Revision ID: b5d93316bd09
Revises: 7fc5208f6540
Create Date: 2024-11-01 18:57:51.593250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d93316bd09'
down_revision: Union[str, None] = '7fc5208f6540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_message_id'), 'ai_message', ['id'], unique=False)
    op.alter_column('scan', 'ai_result',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan', 'ai_result',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_ai_message_id'), table_name='ai_message')
    op.drop_table('ai_message')
    # ### end Alembic commands ###
