"""empty message

Revision ID: b69c859799fd
Revises: 56f5d683273f
Create Date: 2024-11-04 00:22:47.740779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69c859799fd'
down_revision: Union[str, None] = '56f5d683273f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_message', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_message', 'role')
    # ### end Alembic commands ###
