"""empty message

Revision ID: bf4ffa319ef0
Revises: 647c38f9f8b4
Create Date: 2024-11-05 00:22:58.169726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4ffa319ef0'
down_revision: Union[str, None] = '647c38f9f8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('has_segmentation', sa.Boolean(), nullable=True))
    op.add_column('message', sa.Column('segmentation_base64', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'segmentation_base64')
    op.drop_column('message', 'has_segmentation')
    # ### end Alembic commands ###
