"""empty message

Revision ID: c15e78cf3266
Revises: 9b2e33f9c061
Create Date: 2024-11-03 13:07:11.532231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15e78cf3266'
down_revision: Union[str, None] = '9b2e33f9c061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan', 'body_part')
    op.add_column('scan_folder', sa.Column('body_part', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_folder', 'body_part')
    op.add_column('scan', sa.Column('body_part', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
