"""empty message

Revision ID: efa10d726c86
Revises: c15e78cf3266
Create Date: 2024-11-03 13:16:29.803697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa10d726c86'
down_revision: Union[str, None] = 'c15e78cf3266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_folder', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_folder', 'created_at')
    # ### end Alembic commands ###
