"""empty message

Revision ID: f7aec5406578
Revises: bf4ffa319ef0
Create Date: 2024-11-05 01:04:04.601873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7aec5406578'
down_revision: Union[str, None] = 'bf4ffa319ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan', 'have_medicines')
    op.drop_column('scan', 'mixing')
    op.drop_column('scan', 'how_many_days')
    op.drop_column('scan', 'have_pain')
    op.drop_column('scan', 'size')
    op.add_column('scan_folder', sa.Column('size', sa.String(), nullable=True))
    op.add_column('scan_folder', sa.Column('how_many_days', sa.String(), nullable=True))
    op.add_column('scan_folder', sa.Column('have_pain', sa.Boolean(), nullable=True))
    op.add_column('scan_folder', sa.Column('have_medicines', sa.Boolean(), nullable=True))
    op.add_column('scan_folder', sa.Column('mixing', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_folder', 'mixing')
    op.drop_column('scan_folder', 'have_medicines')
    op.drop_column('scan_folder', 'have_pain')
    op.drop_column('scan_folder', 'how_many_days')
    op.drop_column('scan_folder', 'size')
    op.add_column('scan', sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scan', sa.Column('have_pain', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('scan', sa.Column('how_many_days', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scan', sa.Column('mixing', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scan', sa.Column('have_medicines', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
