"""empty message

Revision ID: fbe4188b3096
Revises: 5f14bac40fcd
Create Date: 2024-11-04 10:13:45.397539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe4188b3096'
down_revision: Union[str, None] = '5f14bac40fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('how_many_days', sa.String(), nullable=True),
    sa.Column('image_base64', sa.String(), nullable=True),
    sa.Column('ai_result', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['doctor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_scan_id'), 'doctor_scan', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_scan_id'), table_name='doctor_scan')
    op.drop_table('doctor_scan')
    # ### end Alembic commands ###
